### ISSUE TITLE
Extending mitre-assistant to map Techniques to NIST, STIGs and/or Critical Security Controls

### ISSUE THREAD

**Issue by aboutsecurity** [dfirence/mitre-assistant#22]
Carlos, as discussed, I think it'd be really useful to the blue team community if we can take mitre-assistant a step further and start mapping MITRE techniques/sub techniques NIST CSF (at least identify, protect, detect), as well as potentially DISA STIGs and CSC as mitigations. 

We can discuss details if you want :)

**Comment by dfirence** [comment]
@aboutsecurity 

This might need more info to take this on purposefully.  Lemme know

**Comment by dfirence** [comment]
Opening in future if more info is provided
