### ISSUE TITLE
[Enhancement] Add search lookup for industry verticals

### ISSUE THREAD

**Issue by juushya** [dfirence/mitre-assistant#26]
**Goal** 
Searching for industry verticals targeted by a threat actor

**Enhancement Request**
Extend the search to look up information on industry verticals associated with threat actors (in the Group description). For example, searching for any threat actor targeting Hotel industry:

`mitre-assitant search -m enterprise -t "hotel"`

One of the results would be FIN5 (and so on):
> FIN5 |   | FIN5 is a financially motivated threat group that has targeted personally identifiable information and payment card information. The group has been active since at least 2008 and has targeted the restaurant, gaming, and hotel industries. The group is made up of actors who likely speak Russian.

Thanks.

**Comment by dfirence** [comment]
Hi @juushya 

Excellent! Thank you so much.  The good news is that will be easy based on the code structure, so I am confident I can change this rapidly for you and others.

**The hard part is**, providing the **search terms** you want in a meaningful way, I have some ideas, would welcome your feedback.

### Questions for you

1. How should I standardize the industry verticals for you and others in the world?

Like, if I say `hotel` and some other people in the U.S.A say `retail`. 

A possibility could be find a solid list of industry vertical designations so we can accomodate a more common search term.

2.  Based on #1 above, do you have a list you have used in the past?

e.g., 

[GICS_Industry_Classification_Standard_Model](https://www.msci.com/gics)
[GICS_Industry_Classificiation_Standard](https://en.wikipedia.org/wiki/Global_Industry_Classification_Standard)
[USA_Critical_Infrastructure_Sectors](https://www.cisa.gov/critical-infrastructure-sectors)


3.  Last piece is, in your example, do you want #MitreAssistant to provide a description of the adversary in addition to the techniques it already provides?

I ask based on your example:

```text
FIN5 |   | FIN5 is a financially motivated threat group that has targeted personally identifiable information and payment card information. The group has been active since at least 2008 and has targeted the restaurant, gaming, and hotel industries. The group is made up of actors who likely speak Russian.
````

**Comment by dfirence** [comment]
Any feedback?

**Comment by dfirence** [comment]
Hotels falls in Ramon under Accomodation in RAMON EU Database

@juushya 

lemme know on how this can work based on your thought process.

https://ec.europa.eu/eurostat/ramon/nomenclatures/index.cfm?TargetUrl=LST_NOM_DTL&StrNom=NACE_REV2&StrLanguageCode=EN&IntPcKey=18513704&StrLayoutCode=

**Comment by dfirence** [comment]
Closing this issue with a pending status for about a week. Work is easy, but need info before standardizing search terms.
