### ISSUE TITLE
Add option to search on ttp description

### ISSUE THREAD

**Issue by lcostantino** [dfirence/mitre-assistant#27]

**Comment by dfirence** [comment]
The user now has

* Cmdline Switch to enable searching **by_description**
* Extra Column Names **SEARCH TOKEN**
* Compatible with multiple inputs by comma

**NOTE**: The search term is a partial match against the **technique_description** field which is the human readable or textual representation of the techniques details.

<br />
<br />

## --search-description

The new flag has a short version `-d` or long version `--search-description`.  It is a boolean flag activated after a search term is applied.  The command line help menu screenshot below shows it.

```text
![image](https://user-images.githubusercontent.com/11415591/112708036-e7760c80-8e85-11eb-9568-d7609325b75f.png)
```

![image](https://user-images.githubusercontent.com/11415591/112708044-f8268280-8e85-11eb-92b8-954c67f84796.png)

<br />

<br />

## Searching

When you apply you will now have a **new column** with **yellow color** to give you the experience of knowing which technique's description has your search token.  To use it then do:

```bash
# You need to re-generate the baseline for your matrix
$> mitre-assistant baseline -m enterprise
```

**Then Search**

```bash
$> mitre-assistant search -m enterprise -t "{{ your_term_here }}" --search-description

# Or Short Version

$> mitre-assistant search -m enterprise -t "{{ your_term_here }}" -d
```

<br />

## **Example: Searching For Techniques that mention Telnet**

```text
![image](https://user-images.githubusercontent.com/11415591/112708216-32dcea80-8e87-11eb-88c3-4698152f391e.png)
```

![image](https://user-images.githubusercontent.com/11415591/112708223-36707180-8e87-11eb-8dbc-729ce0c1ca1e.png)

**Comment by dfirence** [comment]
@lcostantino 

The `master` branch has the current code, if you wanna build this and test follow these steps, please:

1. cargo build --release
2. Generate Baseline:  mitre-assistant baseline -m enterprise
3. Start searching

Please confirm if this what you want.

If you do have what you wanted, consider giving me a star instead of burying me coffee :)

**Comment by lcostantino** [comment]
@dfirence  yes it works!. thanks
