### ISSUE TITLE
Evaluate attck crate for working with the matrix

### ISSUE THREAD

**Issue by TedDriggs** [dfirence/mitre-assistant#31]
Earlier this week I released [`attck`](https://crates.io/crates/attck) to provide a good Rust API for working with the ATT&CK matrix (and more generally STIX 2.x). I think it could make this crate's life easier.

I've included a quick-and-dirty example of printing the tactics and techniques [here](https://github.com/TedDriggs/cti/blob/master/attck/examples/print_matrix.rs).

The project is still young, so it might not be ready yet. If you have time to look at it and find gaps, feedback is actively appreciated.

**Comment by dfirence** [comment]
Hi Ted

First off congratulations on the launch and more specifically, thank you for boosting the rust toolkit family with a rust library for ATT&CK.  I also love the idiomatic implementations - great usage!

I have 5 primary reasons, why #MitreAssistant is built without it being a library.

1.  I don’t want STIX compliance or it’s format.  I don’t have a need for these formats at the moment.
2. I don’t want the MitreSchema from their cti, it’s not the data format or structure that helps me.
3. I don’t want a library, I want a self contained binary where we just worry about querying.
4. I don’t want to read 15MBs of the enterprise.json for any query
5. I am focused on serving users that do not code or create their own tools by using a lib.

I believe the approach with libraries is valuable and likely you have the ability to allow tool creators to have faster runtime if your lib can integrate not just as Rust, but you extend the lib to NODEJs and Python as extensions for talented people that need a speed up while they consume your api.

Looked at your repo and the ambitions you have for STIX are great for the community people that leverage this format, stay motivated, I appreciate what you are doing.

**Comment by TedDriggs** [comment]
Thanks for the thoughtful response and the feedback!
